<?php
echo $this->doctype();

if (isset($_SESSION['User']['roleCode'])):
    $roleCode = $_SESSION['User']['roleCode'];
endif;
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('/js/select2/select2.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/fms_js/pager.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        //->prependFile($this->basePath('/js/fms_js/purchase.js'), 'text/javascript', array())

        ;
        ?>

    </head>
    <body>
        <?php if (isset($roleCode) && $roleCode == 'aa') { ?>
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('application') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('FMS Application') ?></a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('application') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('purchase') ?>"><?php echo $this->translate('Purchase') ?></a></li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('report') ?>"><?php echo $this->translate('Reports') ?></a></li>
                        </ul>
                        <ul class="nav navbar-nav">

                            <li class="user-menu-footer">
                                            <!--<a href="javascript:void(0);" class="help"><span class="help-icon"></span>Help</a>-->
                                <a href="<?php echo $this->url('logout') ?>" class="logout-btn">Logout</a>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </nav>
        <?php } ?>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2015 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
